In [1]:
import sys
sys.path.append('../')

import numpy as np
import pandas as pd 

from scripts.analytics import *
from scripts.algorithms import *

In [2]:
name = "productivity"
namex = "Productivity "
d = 11

###knn
graphs = np.load("../graphs/"+name+"_knn_random.npy", allow_pickle=True)
###threshold
graphsx = np.load("../graphs/"+name+"_thresh_random.npy", allow_pickle=True)

# Compute greedy and random algorithms results# Compute greedy and random algorithms results

## Nearest neighbor

In [3]:
summary_df = pd.DataFrame()
greedyalgo_df = pd.DataFrame()
randomalgo_df = pd.DataFrame()

for lz in range(len(graphs)):

    r_edges_random  = graphs[lz]["edges"]
    r_labels_random = graphs[lz]["labels"]

    for Kz in [1, 2, 3, 4, 5]:
        
        df_greedy, df_random, dfz = heuristic_greedy_random(edgesx=r_edges_random, 
                                                            labelsx=r_labels_random, budgetx=Kz)

        dfz["kmax"] =  graphs[lz]["k_max"]
        dfz["n"] = graphs[lz]['n']
        dfz["m"] =  graphs[lz]['m']
        dfz["dataset"] = name+" ("+ str(d) + ")"
        dfz["graphid"] = lz
        
        df_greedy["graphid"] = [lz]*(len(df_greedy))
        df_random["graphid"] = [lz]*(len(df_random))
        
        summary_df = pd.concat([summary_df, dfz], ignore_index=True)
        greedyalgo_df = pd.concat([greedyalgo_df, df_greedy], ignore_index=True)
        randomalgo_df = pd.concat([randomalgo_df, df_random], ignore_index=True)

In [4]:
summary_df.head()

,K,F(Sg+ U Sg-)*,(Sg+ U Sg-)*,F(Sr+ U Sr-)*,(Sr+ U Sr-)*,F(Sg),Sg,F(Sr),Sr,F(Sgfull),...,F(Sg)/F(Sr),F(Sg)/F(Sgfull),F(Sr)/F(Srfull),budgetGreedyTime,budgetRdmTime,kmax,n,m,dataset,graphid
0,1,77.0,{},77.0,{7},77.0,{},77.0,{11},77.0,...,1.0,1.0,1.0,0.006330,0.000230,1,112,32,productivity (11),0
1,2,77.0,{},77.0,"{34, 7}",77.0,{},77.0,"{11, 4}",77.0,...,1.0,1.0,1.0,0.006751,0.000230,1,112,32,productivity (11),0
2,3,77.0,{},77.0,"{34, 18, 7}",77.0,{},77.0,"{27, 11, 4}",77.0,...,1.0,1.0,1.0,0.007343,0.000326,1,112,32,productivity (11),0
3,4,77.0,{},77.0,"{11, 34, 18, 7}",77.0,{},77.0,"{27, 11, 4, 22}",77.0,...,1.0,1.0,1.0,0.007161,0.000239,1,112,32,productivity (11),0
4,5,77.0,{},77.0,"{34, 18, 7, 11, 29}",77.0,{},77.0,"{4, 11, 21, 22, 27}",77.0,...,1.0,1.0,1.0,0.006854,0.000269,1,112,32,productivity (11),0

In [5]:
greedyalgo_df.head()

   [k](T+)  F(S+)  S+  [K-k](T-)  F(S-)  S- S+ U S-  F(S+ U S-)  graphid
0        0   77.0  {}          1   77.0  {}      {}        77.0        0
1        1   77.0  {}          0   77.0  {}      {}        77.0        0
2        0   77.0  {}          2   77.0  {}      {}        77.0        0
3        1   77.0  {}          1   77.0  {}      {}        77.0        0
4        2   77.0  {}          0   77.0  {}      {}        77.0        0

In [6]:
randomalgo_df.head()

,[k](T+),F(S+),S+,[K-k](T-),F(S-),S-,S+ U S-,F(S+ U S-),graphid
0,0,77.0,{},1,77.0,{7},{7},77.0,0
1,1,77.0,{41},0,77.0,{},{41},77.0,0
2,0,77.0,{},2,77.0,"{34, 7}","{34, 7}",77.0,0
3,1,77.0,{41},1,77.0,{7},"{41, 7}",77.0,0
4,2,77.0,"{41, 6}",0,77.0,{},"{41, 6}",77.0,0

## Thresholding

In [7]:
summary_dfx = pd.DataFrame()
greedyalgo_dfx = pd.DataFrame()
randomalgo_dfx = pd.DataFrame()

for lx in range(len(graphsx)):

    r_edges_randomx  = graphsx[lx]["edges"]
    r_labels_randomx  = graphsx[lx]["labels"]

    for Kx in [1, 2, 3, 4, 5]:
        
        df_greedy, df_random, dfx = heuristic_greedy_random(edgesx=r_edges_randomx, 
                                                            labelsx=r_labels_randomx, budgetx=Kx)

        dfx["r"] =  graphsx[lx]["threshold"]
        dfx["n"] = graphsx[lx]['n']
        dfx["m"] =  graphsx[lx]['m']
        dfx["dataset"] = name+" ("+ str(d) + ")"
        dfx["graphid"] = lx
        
        df_greedy["graphid"] = [lx]*(len(df_greedy))
        df_random["graphid"] = [lx]*(len(df_random))
        
        summary_dfx = pd.concat([summary_dfx, dfx], ignore_index=True)
        greedyalgo_dfx = pd.concat([greedyalgo_dfx, df_greedy], ignore_index=True)
        randomalgo_dfx = pd.concat([randomalgo_dfx, df_random], ignore_index=True)

In [8]:
summary_dfx.head()

,K,F(Sg+ U Sg-)*,(Sg+ U Sg-)*,F(Sr+ U Sr-)*,(Sr+ U Sr-)*,F(Sg),Sg,F(Sr),Sr,F(Sgfull),...,F(Sg)/F(Sr),F(Sg)/F(Sgfull),F(Sr)/F(Srfull),budgetGreedyTime,budgetRdmTime,r,n,m,dataset,graphid
0,1,96.845464,{2},88.545778,{9},96.845464,{2},88.194736,{40},104.0,...,1.098087,0.931206,0.848026,0.071540,0.001525,4.0,112,50,productivity (11),0
1,2,103.500000,"{2, 31}",88.760239,"{9, 29}",103.500000,"{2, 31}",88.385736,"{40, 7}",104.0,...,1.171003,0.995192,0.849863,0.143423,0.000944,4.0,112,50,productivity (11),0
2,3,104.000000,"{16, 2, 31}",88.951239,"{9, 29, 7}",104.000000,"{16, 2, 31}",88.830180,"{40, 1, 7}",104.0,...,1.170773,1.000000,0.854136,0.206981,0.001401,4.0,112,50,productivity (11),0
3,4,104.000000,"{16, 2, 31}",102.560160,"{9, 20, 1, 22}",104.000000,"{16, 2, 31}",89.115895,"{40, 1, 47, 7}",104.0,...,1.167020,1.000000,0.856884,0.252051,0.000898,4.0,112,50,productivity (11),0
4,5,104.000000,"{16, 2, 31}",102.795455,"{1, 19, 20, 22, 9}",104.000000,"{16, 2, 31}",89.115895,"{1, 7, 40, 47, 17}",104.0,...,1.167020,1.000000,0.856884,0.324906,0.001704,4.0,112,50,productivity (11),0

In [9]:
greedyalgo_dfx.head()

,[k](T+),F(S+),S+,[K-k](T-),F(S-),S-,S+ U S-,F(S+ U S-),graphid
0,0,80.725188,{},1,83.165345,{8},{8},83.165345,0
1,1,96.845464,{2},0,80.725188,{},{2},96.845464,0
2,0,80.725188,{},2,85.728326,"{8, 44}","{8, 44}",85.728326,0
3,1,96.845464,{2},1,83.165345,{8},"{8, 2}",97.406783,0
4,2,103.500000,"{2, 31}",0,80.725188,{},"{2, 31}",103.500000,0

In [10]:
randomalgo_dfx.head()

,[k](T+),F(S+),S+,[K-k](T-),F(S-),S-,S+ U S-,F(S+ U S-),graphid
0,0,80.725188,{},1,81.343001,{29},{29},81.343001,0
1,1,88.545778,{9},0,80.725188,{},{9},88.545778,0
2,0,80.725188,{},2,81.589618,"{29, 7}","{29, 7}",81.589618,0
3,1,88.545778,{9},1,81.343001,{29},"{9, 29}",88.760239,0
4,2,88.653886,"{9, 1}",0,80.725188,{},"{9, 1}",88.653886,0

# Save Results

In [11]:
summary_df.to_csv("./sm_results/"+name+"_knn_summary.csv", index=False)
greedyalgo_df.to_csv("./sm_results/"+name+"_knn_greedyheuristic.csv", index=False)
randomalgo_df.to_csv("./sm_results/"+name+"_knn_randomheuristic.csv", index=False)


summary_dfx.to_csv("./sm_results/"+name+"_thresh_summary.csv", index=False)
greedyalgo_dfx.to_csv("./sm_results/"+name+"_thresh_greedyheuristic.csv", index=False)
randomalgo_dfx.to_csv("./sm_results/"+name+"_thresh_randomheuristic.csv", index=False)