In [1]:
import sys
sys.path.append('../')

import numpy as np
import pandas as pd 

from scripts.analytics import *
from scripts.algorithms import *

In [2]:
name = "adult"
namex = "Adult "

d = 14


###knn
graphs = np.load("../graphs/"+name+"_knn_random.npy", allow_pickle=True)
###threshold
graphsx = np.load("../graphs/"+name+"_thresh_random.npy", allow_pickle=True)

# Compute greedy and random algorithms results

## Nearest neighbor

In [3]:
summary_df = pd.DataFrame()
greedyalgo_df = pd.DataFrame()
randomalgo_df = pd.DataFrame()

for lz in range(len(graphs)):

    r_edges_random  = graphs[lz]["edges"]
    r_labels_random = graphs[lz]["labels"]

    for Kz in [1, 2, 3, 4, 5]:
        
        df_greedy, df_random, dfz = heuristic_greedy_random(edgesx=r_edges_random, 
                                                            labelsx=r_labels_random, budgetx=Kz)

        dfz["kmax"] =  graphs[lz]["k_max"]
        dfz["n"] = graphs[lz]['n']
        dfz["m"] =  graphs[lz]['m']
        dfz["dataset"] = name+" ("+ str(d) + ")"
        dfz["graphid"] = lz
        
        df_greedy["graphid"] = [lz]*(len(df_greedy))
        df_random["graphid"] = [lz]*(len(df_random))
        
        summary_df = pd.concat([summary_df, dfz], ignore_index=True)
        greedyalgo_df = pd.concat([greedyalgo_df, df_greedy], ignore_index=True)
        randomalgo_df = pd.concat([randomalgo_df, df_random], ignore_index=True)

In [4]:
summary_df.head()

,K,F(Sg+ U Sg-)*,(Sg+ U Sg-)*,F(Sr+ U Sr-)*,(Sr+ U Sr-)*,F(Sg),Sg,F(Sr),Sr,F(Sgfull),...,F(Sg)/F(Sr),F(Sg)/F(Sgfull),F(Sr)/F(Srfull),budgetGreedyTime,budgetRdmTime,kmax,n,m,dataset,graphid
0,1,70.0,{},70.0,{14},70.0,{},70.0,{44},70.0,...,1.0,1.0,1.0,0.028980,0.000580,1,328,46,adult (14),0
1,2,70.0,{},70.0,"{1, 14}",70.0,{},70.0,"{44, 7}",70.0,...,1.0,1.0,1.0,0.030322,0.000775,1,328,46,adult (14),0
2,3,70.0,{},70.0,"{1, 14, 25}",70.0,{},70.0,"{1, 44, 7}",70.0,...,1.0,1.0,1.0,0.028137,0.000921,1,328,46,adult (14),0
3,4,70.0,{},70.0,"{1, 23, 14, 25}",70.0,{},70.0,"{1, 44, 17, 7}",70.0,...,1.0,1.0,1.0,0.029242,0.000606,1,328,46,adult (14),0
4,5,70.0,{},70.0,"{1, 22, 23, 25, 14}",70.0,{},70.0,"{1, 7, 44, 15, 17}",70.0,...,1.0,1.0,1.0,0.032377,0.000937,1,328,46,adult (14),0

In [5]:
greedyalgo_df.head()

   [k](T+)  F(S+)  S+  [K-k](T-)  F(S-)  S- S+ U S-  F(S+ U S-)  graphid
0        0   70.0  {}          1   70.0  {}      {}        70.0        0
1        1   70.0  {}          0   70.0  {}      {}        70.0        0
2        0   70.0  {}          2   70.0  {}      {}        70.0        0
3        1   70.0  {}          1   70.0  {}      {}        70.0        0
4        2   70.0  {}          0   70.0  {}      {}        70.0        0

In [6]:
randomalgo_df.head()

,[k](T+),F(S+),S+,[K-k](T-),F(S-),S-,S+ U S-,F(S+ U S-),graphid
0,0,70.0,{},1,70.0,{14},{14},70.0,0
1,1,70.0,{5},0,70.0,{},{5},70.0,0
2,0,70.0,{},2,70.0,"{1, 14}","{1, 14}",70.0,0
3,1,70.0,{5},1,70.0,{14},"{5, 14}",70.0,0
4,2,70.0,"{3, 5}",0,70.0,{},"{3, 5}",70.0,0

## Thresholding

In [7]:
summary_dfx = pd.DataFrame()
greedyalgo_dfx = pd.DataFrame()
randomalgo_dfx = pd.DataFrame()

for lx in range(len(graphsx)):

    r_edges_randomx  = graphsx[lx]["edges"]
    r_labels_randomx  = graphsx[lx]["labels"]

    for Kx in [1, 2, 3, 4, 5]:
        
        df_greedy, df_random, dfx = heuristic_greedy_random(edgesx=r_edges_randomx, 
                                                            labelsx=r_labels_randomx, budgetx=Kx)

        dfx["r"] =  graphsx[lx]["threshold"]
        dfx["n"] = graphsx[lx]['n']
        dfx["m"] =  graphsx[lx]['m']
        dfx["dataset"] = name+" ("+ str(d) + ")"
        dfx["graphid"] = lx
        
        df_greedy["graphid"] = [lx]*(len(df_greedy))
        df_random["graphid"] = [lx]*(len(df_random))
        
        summary_dfx = pd.concat([summary_dfx, dfx], ignore_index=True)
        greedyalgo_dfx = pd.concat([greedyalgo_dfx, df_greedy], ignore_index=True)
        randomalgo_dfx = pd.concat([randomalgo_dfx, df_random], ignore_index=True)

In [8]:
summary_dfx.head()

,K,F(Sg+ U Sg-)*,(Sg+ U Sg-)*,F(Sr+ U Sr-)*,(Sr+ U Sr-)*,F(Sg),Sg,F(Sr),Sr,F(Sgfull),...,F(Sg)/F(Sr),F(Sg)/F(Sgfull),F(Sr)/F(Srfull),budgetGreedyTime,budgetRdmTime,r,n,m,dataset,graphid
0,1,202.512964,{5},102.700900,{18},202.512964,{5},78.528840,{42},242.0,...,2.578836,0.836830,0.324499,0.151982,0.003004,4.0,328,48,adult (14),0
1,2,231.237085,"{9, 5}",203.679630,"{18, 5}",231.237085,"{9, 5}",78.528840,"{42, 7}",242.0,...,2.944614,0.955525,0.324499,0.278429,0.003456,4.0,328,48,adult (14),0
2,3,235.492857,"{8, 9, 5}",205.779630,"{18, 3, 5}",235.492857,"{8, 9, 5}",81.264813,"{1, 42, 7}",242.0,...,2.897845,0.973111,0.335805,0.401953,0.003323,4.0,328,48,adult (14),0
3,4,237.876190,"{8, 9, 5, 46}",234.503752,"{9, 18, 3, 5}",237.876190,"{8, 9, 5, 46}",81.868296,"{1, 42, 49, 7}",242.0,...,2.905596,0.982959,0.338299,0.487868,0.001661,4.0,328,48,adult (14),0
4,5,239.976190,"{3, 5, 8, 9, 46}",238.759524,"{18, 3, 5, 8, 9}",239.976190,"{3, 5, 8, 9, 46}",107.537818,"{1, 7, 42, 49, 18}",242.0,...,2.231552,0.991637,0.444371,0.720932,0.003243,4.0,328,48,adult (14),0

In [9]:
greedyalgo_dfx.head()

,[k](T+),F(S+),S+,[K-k](T-),F(S-),S-,S+ U S-,F(S+ U S-),graphid
0,0,76.838574,{},1,80.599759,{22},{22},80.599759,0
1,1,202.512964,{5},0,76.838574,{},{5},202.512964,0
2,0,76.838574,{},2,85.317253,"{1, 22}","{1, 22}",85.317253,0
3,1,202.512964,{5},1,80.599759,{22},"{5, 22}",204.313276,0
4,2,231.237085,"{9, 5}",0,76.838574,{},"{9, 5}",231.237085,0

In [10]:
randomalgo_dfx.head()

,[k](T+),F(S+),S+,[K-k](T-),F(S-),S-,S+ U S-,F(S+ U S-),graphid
0,0,76.838574,{},1,78.701149,{14},{14},78.701149,0
1,1,102.700900,{18},0,76.838574,{},{18},102.700900,0
2,0,76.838574,{},2,81.420155,"{1, 14}","{1, 14}",81.420155,0
3,1,102.700900,{18},1,78.701149,{14},"{18, 14}",104.169909,0
4,2,203.679630,"{18, 5}",0,76.838574,{},"{18, 5}",203.679630,0

# Save Results

In [11]:
summary_df.to_csv("./sm_results/"+name+"_knn_summary.csv", index=False)
greedyalgo_df.to_csv("./sm_results/"+name+"_knn_greedyheuristic.csv", index=False)
randomalgo_df.to_csv("./sm_results/"+name+"_knn_randomheuristic.csv", index=False)


summary_dfx.to_csv("./sm_results/"+name+"_thresh_summary.csv", index=False)
greedyalgo_dfx.to_csv("./sm_results/"+name+"_thresh_greedyheuristic.csv", index=False)
randomalgo_dfx.to_csv("./sm_results/"+name+"_thresh_randomheuristic.csv", index=False)