In [1]:
import sys
sys.path.append('../')

import numpy as np
import pandas as pd 

from scripts.analytics import *
from scripts.algorithms import *

In [2]:
name = "studentportuguese"
namex = "Student-portuguese "

d = 30

###knn
graphs = np.load("../graphs/"+name+"_knn_random.npy", allow_pickle=True)
###threshold
graphsx = np.load("../graphs/"+name+"_thresh_random.npy", allow_pickle=True)

# Compute greedy and random algorithms results# Compute greedy and random algorithms results

## Nearest neighbor

In [3]:
summary_df = pd.DataFrame()
greedyalgo_df = pd.DataFrame()
randomalgo_df = pd.DataFrame()

for lz in range(len(graphs)):

    r_edges_random  = graphs[lz]["edges"]
    r_labels_random = graphs[lz]["labels"]

    for Kz in [1, 2, 3, 4, 5]:
        
        df_greedy, df_random, dfz = heuristic_greedy_random(edgesx=r_edges_random, 
                                                            labelsx=r_labels_random, budgetx=Kz)

        dfz["kmax"] =  graphs[lz]["k_max"]
        dfz["n"] = graphs[lz]['n']
        dfz["m"] =  graphs[lz]['m']
        dfz["dataset"] = name+" ("+ str(d) + ")"
        dfz["graphid"] = lz
        
        df_greedy["graphid"] = [lz]*(len(df_greedy))
        df_random["graphid"] = [lz]*(len(df_random))
        
        summary_df = pd.concat([summary_df, dfz], ignore_index=True)
        greedyalgo_df = pd.concat([greedyalgo_df, df_greedy], ignore_index=True)
        randomalgo_df = pd.concat([randomalgo_df, df_random], ignore_index=True)

In [4]:
summary_df.head()

,K,F(Sg+ U Sg-)*,(Sg+ U Sg-)*,F(Sr+ U Sr-)*,(Sr+ U Sr-)*,F(Sg),Sg,F(Sr),Sr,F(Sgfull),...,F(Sg)/F(Sr),F(Sg)/F(Sgfull),F(Sr)/F(Srfull),budgetGreedyTime,budgetRdmTime,kmax,n,m,dataset,graphid
0,1,109.0,{},109.0,{38},109.0,{},109.0,{44},109.0,...,1.0,1.0,1.0,0.027287,0.000708,1,224,46,studentportuguese (30),0
1,2,109.0,{},109.0,"{4, 38}",109.0,{},109.0,"{44, 7}",109.0,...,1.0,1.0,1.0,0.023619,0.000450,1,224,46,studentportuguese (30),0
2,3,109.0,{},109.0,"{1, 4, 38}",109.0,{},109.0,"{1, 44, 7}",109.0,...,1.0,1.0,1.0,0.031862,0.000650,1,224,46,studentportuguese (30),0
3,4,109.0,{},109.0,"{46, 1, 4, 38}",109.0,{},109.0,"{1, 18, 44, 7}",109.0,...,1.0,1.0,1.0,0.034420,0.000778,1,224,46,studentportuguese (30),0
4,5,109.0,{},109.0,"{1, 4, 38, 11, 46}",109.0,{},109.0,"{1, 7, 44, 16, 18}",109.0,...,1.0,1.0,1.0,0.024233,0.000594,1,224,46,studentportuguese (30),0

In [5]:
greedyalgo_df.head()

   [k](T+)  F(S+)  S+  [K-k](T-)  F(S-)  S- S+ U S-  F(S+ U S-)  graphid
0        0  109.0  {}          1  109.0  {}      {}       109.0        0
1        1  109.0  {}          0  109.0  {}      {}       109.0        0
2        0  109.0  {}          2  109.0  {}      {}       109.0        0
3        1  109.0  {}          1  109.0  {}      {}       109.0        0
4        2  109.0  {}          0  109.0  {}      {}       109.0        0

In [6]:
randomalgo_df.head()

,[k](T+),F(S+),S+,[K-k](T-),F(S-),S-,S+ U S-,F(S+ U S-),graphid
0,0,109.0,{},1,109.0,{38},{38},109.0,0
1,1,109.0,{13},0,109.0,{},{13},109.0,0
2,0,109.0,{},2,109.0,"{4, 38}","{4, 38}",109.0,0
3,1,109.0,{13},1,109.0,{38},"{13, 38}",109.0,0
4,2,109.0,"{0, 13}",0,109.0,{},"{0, 13}",109.0,0

## Thresholding

In [7]:
summary_dfx = pd.DataFrame()
greedyalgo_dfx = pd.DataFrame()
randomalgo_dfx = pd.DataFrame()

for lx in range(len(graphsx)):

    r_edges_randomx  = graphsx[lx]["edges"]
    r_labels_randomx  = graphsx[lx]["labels"]

    for Kx in [1, 2, 3, 4, 5]:
        
        df_greedy, df_random, dfx = heuristic_greedy_random(edgesx=r_edges_randomx, 
                                                            labelsx=r_labels_randomx, budgetx=Kx)

        dfx["r"] =  graphsx[lx]["threshold"]
        dfx["n"] = graphsx[lx]['n']
        dfx["m"] =  graphsx[lx]['m']
        dfx["dataset"] = name+" ("+ str(d) + ")"
        dfx["graphid"] = lx
        
        df_greedy["graphid"] = [lx]*(len(df_greedy))
        df_random["graphid"] = [lx]*(len(df_random))
        
        summary_dfx = pd.concat([summary_dfx, dfx], ignore_index=True)
        greedyalgo_dfx = pd.concat([greedyalgo_dfx, df_greedy], ignore_index=True)
        randomalgo_dfx = pd.concat([randomalgo_dfx, df_random], ignore_index=True)

In [8]:
summary_dfx.head()

,K,F(Sg+ U Sg-)*,(Sg+ U Sg-)*,F(Sr+ U Sr-)*,(Sr+ U Sr-)*,F(Sg),Sg,F(Sr),Sr,F(Sgfull),...,F(Sg)/F(Sr),F(Sg)/F(Sgfull),F(Sr)/F(Srfull),budgetGreedyTime,budgetRdmTime,r,n,m,dataset,graphid
0,1,5.0,{32},5.0,{32},5.0,{32},5.0,{28},5.0,...,1.0,1.0,1.0,0.002330,0.000321,4.0,224,6,studentportuguese (30),0
1,2,5.0,{32},5.0,{32},5.0,{32},5.0,"{32, 28}",5.0,...,1.0,1.0,1.0,0.007512,0.000632,4.0,224,6,studentportuguese (30),0
2,3,5.0,{32},5.0,{32},5.0,{32},5.0,"{32, 41, 28}",5.0,...,1.0,1.0,1.0,0.005219,0.000641,4.0,224,6,studentportuguese (30),0
3,4,5.0,{32},5.0,{32},5.0,{32},5.0,"{32, 41, 18, 28}",5.0,...,1.0,1.0,1.0,0.007218,0.000636,4.0,224,6,studentportuguese (30),0
4,5,5.0,{32},5.0,{32},5.0,{32},5.0,"{32, 41, 16, 18, 28}",5.0,...,1.0,1.0,1.0,0.006605,0.000649,4.0,224,6,studentportuguese (30),0

In [9]:
greedyalgo_dfx.head()

,[k](T+),F(S+),S+,[K-k](T-),F(S-),S-,S+ U S-,F(S+ U S-),graphid
0,0,4.666667,{},1,5.000000,{32},{32},5.0,0
1,1,5.000000,{41},0,4.666667,{},{41},5.0,0
2,0,4.666667,{},2,5.000000,{32},{32},5.0,0
3,1,5.000000,{41},1,5.000000,{32},"{32, 41}",5.0,0
4,2,5.000000,{41},0,4.666667,{},{41},5.0,0

In [10]:
randomalgo_dfx.head()

,[k](T+),F(S+),S+,[K-k](T-),F(S-),S-,S+ U S-,F(S+ U S-),graphid
0,0,4.666667,{},1,5.000000,{32},{32},5.000000,0
1,1,4.666667,{16},0,4.666667,{},{16},4.666667,0
2,0,4.666667,{},2,5.000000,{32},{32},5.000000,0
3,1,4.666667,{16},1,5.000000,{32},"{16, 32}",5.000000,0
4,2,5.000000,"{16, 28}",0,4.666667,{},"{16, 28}",5.000000,0

# Save Results

In [11]:
summary_df.to_csv("./sm_results/"+name+"_knn_summary.csv", index=False)
greedyalgo_df.to_csv("./sm_results/"+name+"_knn_greedyheuristic.csv", index=False)
randomalgo_df.to_csv("./sm_results/"+name+"_knn_randomheuristic.csv", index=False)


summary_dfx.to_csv("./sm_results/"+name+"_thresh_summary.csv", index=False)
greedyalgo_dfx.to_csv("./sm_results/"+name+"_thresh_greedyheuristic.csv", index=False)
randomalgo_dfx.to_csv("./sm_results/"+name+"_thresh_randomheuristic.csv", index=False)