In [1]:
import sys
sys.path.append('../')

import numpy as np
import pandas as pd 

from scripts.analytics import *
from scripts.algorithms import *

In [2]:
name = "studentmath"
namex = "Student-mat "
d = 30

###knn
graphs = np.load("../graphs/"+name+"_knn_random.npy", allow_pickle=True)
###threshold
graphsx = np.load("../graphs/"+name+"_thresh_random.npy", allow_pickle=True)

# Compute greedy and random algorithms results# Compute greedy and random algorithms results

## Nearest neighbor

In [3]:
summary_df = pd.DataFrame()
greedyalgo_df = pd.DataFrame()
randomalgo_df = pd.DataFrame()

for lz in range(len(graphs)):

    r_edges_random  = graphs[lz]["edges"]
    r_labels_random = graphs[lz]["labels"]

    for Kz in [1, 2, 3, 4, 5]:
        
        df_greedy, df_random, dfz = heuristic_greedy_random(edgesx=r_edges_random, 
                                                            labelsx=r_labels_random, budgetx=Kz)

        dfz["kmax"] =  graphs[lz]["k_max"]
        dfz["n"] = graphs[lz]['n']
        dfz["m"] =  graphs[lz]['m']
        dfz["dataset"] = name+" ("+ str(d) + ")"
        dfz["graphid"] = lz
        
        df_greedy["graphid"] = [lz]*(len(df_greedy))
        df_random["graphid"] = [lz]*(len(df_random))
        
        summary_df = pd.concat([summary_df, dfz], ignore_index=True)
        greedyalgo_df = pd.concat([greedyalgo_df, df_greedy], ignore_index=True)
        randomalgo_df = pd.concat([randomalgo_df, df_random], ignore_index=True)

In [4]:
summary_df.head()

,K,F(Sg+ U Sg-)*,(Sg+ U Sg-)*,F(Sr+ U Sr-)*,(Sr+ U Sr-)*,F(Sg),Sg,F(Sr),Sr,F(Sgfull),...,F(Sg)/F(Sr),F(Sg)/F(Sgfull),F(Sr)/F(Srfull),budgetGreedyTime,budgetRdmTime,kmax,n,m,dataset,graphid
0,1,106.0,{},106.0,{8},106.0,{},106.0,{7},106.0,...,1.0,1.0,1.0,0.014505,0.000386,1,206,35,studentmath (30),0
1,2,106.0,{},106.0,"{8, 3}",106.0,{},106.0,"{1, 7}",106.0,...,1.0,1.0,1.0,0.014144,0.000740,1,206,35,studentmath (30),0
2,3,106.0,{},106.0,"{8, 3, 15}",106.0,{},106.0,"{1, 19, 7}",106.0,...,1.0,1.0,1.0,0.012386,0.000501,1,206,35,studentmath (30),0
3,4,106.0,{},106.0,"{8, 3, 14, 15}",106.0,{},106.0,"{1, 19, 15, 7}",106.0,...,1.0,1.0,1.0,0.013439,0.000402,1,206,35,studentmath (30),0
4,5,106.0,{},106.0,"{3, 37, 8, 14, 15}",106.0,{},106.0,"{1, 7, 14, 15, 19}",106.0,...,1.0,1.0,1.0,0.015760,0.000402,1,206,35,studentmath (30),0

In [5]:
greedyalgo_df.head()

   [k](T+)  F(S+)  S+  [K-k](T-)  F(S-)  S- S+ U S-  F(S+ U S-)  graphid
0        0  106.0  {}          1  106.0  {}      {}       106.0        0
1        1  106.0  {}          0  106.0  {}      {}       106.0        0
2        0  106.0  {}          2  106.0  {}      {}       106.0        0
3        1  106.0  {}          1  106.0  {}      {}       106.0        0
4        2  106.0  {}          0  106.0  {}      {}       106.0        0

In [6]:
randomalgo_df.head()

,[k](T+),F(S+),S+,[K-k](T-),F(S-),S-,S+ U S-,F(S+ U S-),graphid
0,0,106.0,{},1,106.0,{8},{8},106.0,0
1,1,106.0,{6},0,106.0,{},{6},106.0,0
2,0,106.0,{},2,106.0,"{8, 3}","{8, 3}",106.0,0
3,1,106.0,{6},1,106.0,{8},"{8, 6}",106.0,0
4,2,106.0,"{0, 6}",0,106.0,{},"{0, 6}",106.0,0

## Thresholding

In [7]:
summary_dfx = pd.DataFrame()
greedyalgo_dfx = pd.DataFrame()
randomalgo_dfx = pd.DataFrame()

for lx in range(len(graphsx)):

    r_edges_randomx  = graphsx[lx]["edges"]
    r_labels_randomx  = graphsx[lx]["labels"]

    for Kx in [1, 2, 3, 4, 5]:
        
        df_greedy, df_random, dfx = heuristic_greedy_random(edgesx=r_edges_randomx, 
                                                            labelsx=r_labels_randomx, budgetx=Kx)

        dfx["r"] =  graphsx[lx]["threshold"]
        dfx["n"] = graphsx[lx]['n']
        dfx["m"] =  graphsx[lx]['m']
        dfx["dataset"] = name+" ("+ str(d) + ")"
        dfx["graphid"] = lx
        
        df_greedy["graphid"] = [lx]*(len(df_greedy))
        df_random["graphid"] = [lx]*(len(df_random))
        
        summary_dfx = pd.concat([summary_dfx, dfx], ignore_index=True)
        greedyalgo_dfx = pd.concat([greedyalgo_dfx, df_greedy], ignore_index=True)
        randomalgo_dfx = pd.concat([randomalgo_dfx, df_random], ignore_index=True)

In [8]:
summary_dfx.head()

,K,F(Sg+ U Sg-)*,(Sg+ U Sg-)*,F(Sr+ U Sr-)*,(Sr+ U Sr-)*,F(Sg),Sg,F(Sr),Sr,F(Sgfull),...,F(Sg)/F(Sr),F(Sg)/F(Sgfull),F(Sr)/F(Srfull),budgetGreedyTime,budgetRdmTime,r,n,m,dataset,graphid
0,1,11.0,{17},11.0,{17},11.0,{0},10.5,{3},11.0,...,1.047619,1.0,0.954545,0.006476,0.000978,4.0,206,9,studentmath (30),0
1,2,11.0,{17},11.0,"{17, 36}",11.0,{0},11.0,"{0, 3}",11.0,...,1.000000,1.0,1.000000,0.011287,0.000574,4.0,206,9,studentmath (30),0
2,3,11.0,{17},11.0,"{17, 10, 36}",11.0,{0},11.0,"{0, 9, 3}",11.0,...,1.000000,1.0,1.000000,0.013919,0.000618,4.0,206,9,studentmath (30),0
3,4,11.0,{17},11.0,"{17, 10, 3, 36}",11.0,{0},11.0,"{0, 9, 3, 36}",11.0,...,1.000000,1.0,1.000000,0.010249,0.000535,4.0,206,9,studentmath (30),0
4,5,11.0,{17},11.0,"{17, 10, 3, 36}",11.0,{0},11.0,"{0, 3, 36, 9, 24}",11.0,...,1.000000,1.0,1.000000,0.008815,0.000403,4.0,206,9,studentmath (30),0

In [9]:
greedyalgo_dfx.head()

   [k](T+)  F(S+)   S+  [K-k](T-)  F(S-)    S-  S+ U S-  F(S+ U S-)  graphid
0        0   10.5   {}          1   11.0  {17}     {17}        11.0        0
1        1   11.0  {0}          0   10.5    {}      {0}        11.0        0
2        0   10.5   {}          2   11.0  {17}     {17}        11.0        0
3        1   11.0  {0}          1   11.0  {17}  {0, 17}        11.0        0
4        2   11.0  {0}          0   10.5    {}      {0}        11.0        0

In [10]:
randomalgo_dfx.head()

,[k](T+),F(S+),S+,[K-k](T-),F(S-),S-,S+ U S-,F(S+ U S-),graphid
0,0,10.5,{},1,11.0,{17},{17},11.0,0
1,1,11.0,{0},0,10.5,{},{0},11.0,0
2,0,10.5,{},2,11.0,"{17, 36}","{17, 36}",11.0,0
3,1,11.0,{0},1,11.0,{17},"{0, 17}",11.0,0
4,2,11.0,"{0, 9}",0,10.5,{},"{0, 9}",11.0,0

# Save Results

In [11]:
summary_df.to_csv("./sm_results/"+name+"_knn_summary.csv", index=False)
greedyalgo_df.to_csv("./sm_results/"+name+"_knn_greedyheuristic.csv", index=False)
randomalgo_df.to_csv("./sm_results/"+name+"_knn_randomheuristic.csv", index=False)


summary_dfx.to_csv("./sm_results/"+name+"_thresh_summary.csv", index=False)
greedyalgo_dfx.to_csv("./sm_results/"+name+"_thresh_greedyheuristic.csv", index=False)
randomalgo_dfx.to_csv("./sm_results/"+name+"_thresh_randomheuristic.csv", index=False)